In [1]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [67, 88, 75],
    [90, 94, 89],
    [76, 64, 70],
    [82, 79, 85]
])

avg_per_student = np.mean(marks, axis=1)
min_per_student = np.min(marks, axis=1)
max_per_student = np.max(marks, axis=1)

print("Marks Array:\n", marks)
print("\nAverage Marks per Student:", avg_per_student)
print("Minimum Marks per Student:", min_per_student)
print("Maximum Marks per Student:", max_per_student)

print("\nMarks of 2nd and 4th student:\n", marks[[1, 3]])

high_scorers = np.any(marks > 80, axis=1)
print("\nStudents scoring above 80 in any subject:\n", marks[high_scorers])

reshaped = marks.T
print("\nReshaped Array (Subject-wise):\n", reshaped)

Marks Array:
 [[85 78 92]
 [67 88 75]
 [90 94 89]
 [76 64 70]
 [82 79 85]]

Average Marks per Student: [85.         76.66666667 91.         70.         82.        ]
Minimum Marks per Student: [78 67 89 64 79]
Maximum Marks per Student: [92 88 94 76 85]

Marks of 2nd and 4th student:
 [[67 88 75]
 [76 64 70]]

Students scoring above 80 in any subject:
 [[85 78 92]
 [67 88 75]
 [90 94 89]
 [82 79 85]]

Reshaped Array (Subject-wise):
 [[85 67 90 76 82]
 [78 88 94 64 79]
 [92 75 89 70 85]]
