In [5]:
import numpy as np
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

add = np.add(mat1, mat2)
sub = np.subtract(mat1, mat2)

print("Addition: \n", add)
print("Subtraction: \n", sub)

Addition: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction: 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [4]:
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

dot_res = np.dot(a, b)
print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("Dot Product Result:\n", dot_res)


Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Dot Product Result:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [6]:
file_name = "student_data.txt"

name = input("Enter name: ")
marks = input("Enter marks: ")

with open(file_name, "a") as f:
    f.write(f"{name},{marks}\n")

print("\nAll Entries:")
with open(file_name, "r") as f:
    for line in f:
        n, m = line.strip().split(",")
        print(f"Name: {n}, Marks: {m}")

Enter name: student 
Enter marks: 40

All Entries:
Name: student , Marks: 40
